# Conclusion

***In this Session***

1. [Content Review](#content-review)
2. [Resources](#resources)
3. [References](#references)

## Content Review

1. Congratulations on completing the training materials. The content from this training package is intended to be an additional compilation of resources to aid you in your personal and professional endeavors to convey compelling visual stories from well-managed data sets. If you have any feedback or comments on this training that you'd like to share, please use this [feedback survey](https://forms.gle/QteqpUKG5dNMkBA).
1. While the materials can be valuable for an individual, greater value can come from collaborating over these materials with colleagues with related roles throughout your organization. Remember that there are many roles in data science communication and the information passes through many phases and hands before ultimately getting to a target audience. Familiarity with your “data role,” and the role of your work partners will ultimately aid in the full data storytelling process.
1. While this training can be an informative leap into data sciences, the greatest experience comes with repetitive practice on new topic areas. Consider these resources as a reference point to be reviewed intermittently when you need a reminder about key steps or best practices in managing, visualizing, or communicating data messages.

## Resources

1. The table below provides direct links to all of the files from each Module and Session. The full zipped package can be accessed and downloaded using this link.
      
+----------------+-------------------------------------+----------------------------------------------+
| **Module**     | **Session**                         | **Relevant Resources**                       |
+----------------+-------------------------------------+----------------------------------------------+
|2. Data         |1. Data Management                   |  - [Metadata template](files/metadata_template_blank.xlsx)                                            |
+----------------+-------------------------------------+----------------------------------------------+
|                |2. Data Cleaning                     |  - [Data cleaning checklist](files/data_processing_checklist.docx)                                            |
+----------------+-------------------------------------+----------------------------------------------+
|                |3. Normalization and Standardization | - Data Cleaning [Exercise](files/M2S3_exercise.xlsx) and [Key](files/M2S3_exercise_key.xlsx)             |
+----------------+-------------------------------------+----------------------------------------------+
|3. Tableau      |1. Tableau Basics                    | - [CRM_Fish_edit](files/CRM_Fish_edit.xlsx)                              |
+----------------+-------------------------------------+----------------------------------------------+
|                |2. Tableau Skills: Part 1            | - [M3S2 Progress Check Workbook](files/M3S2_exercise_key.twbx)               |
+----------------+-------------------------------------+----------------------------------------------+
|                |3. Tableau Skills: Part 2            | - [M3S3 Progress Check Workbook](files/M3S3_exercise_key.twbx)               |
+----------------+-------------------------------------+----------------------------------------------+
|                |4. Tableau Skills: Part 3            | - [Biomass as a Calculated Field Slides](files/M3S4_calculated_field_biomass_example.pdf)       |
+----------------+-------------------------------------+----------------------------------------------+
|                |5. Tableau Dashboards: Part 1        | - [Map Making Homework File](files/M3S5_exercise_key.twbx)                   |
+----------------+-------------------------------------+----------------------------------------------+
|                |6. Tableau Dashboards: Part 2        | - M3S6 Progress Check Workbook               |
+----------------+-------------------------------------+----------------------------------------------+
|                |7. Publishing to the web             |                                              |
+----------------+-------------------------------------+----------------------------------------------+
|4. Storytelling |1. Communication Principles          | - [Message Box Workbook](https://www.compassscicomm.org/wp-content/uploads/2020/05/The-Message-Box-Workbook.pdf)                       |
+----------------+-------------------------------------+----------------------------------------------+
|                |                                     | - [Message Box Blank](files/Message-Box-Blank.pdf)                          |
+----------------+-------------------------------------+----------------------------------------------+
|                |2. Data Storytelling                 | - [Identify Your Audience Handout and Exercise](files/M4S2_Data_Storytelling_Audience_Handout_Exercise.pdf)|
|                |                                     | - [Data Storytelling Brief](files/M4S2_Data_Storytelling_Brief.pdf)                    |
+----------------+-------------------------------------+----------------------------------------------+
|                |3. Working with Graphic Designers    | - [Working with Graphic Designers Brief](files/M4S3_Working_With_Graphic_Designers_Brief.pdf)       |
+----------------+-------------------------------------+----------------------------------------------+

## References

   - Cash, David, William C. Clark, Frank Alcock, Nancy M. Dickson, Noelle Eckley, Jill Jäger. “Salience, Credibility, Legitimacy and Boundaries: Linking Research, Assessment and Decision Making,” KSG Working Papers Series, 2003. http://nrs.harvard.edu/urn-3:HUL.InstRepos:32067415 
   - Lowndes,Julia S. Stewart, Benjamin D. Best, Courtney Scarborough, Jamie C. Afflerbach, Melanie R. Frazier, Casey C. O’hara, Ning Jiang, Benjamin S. Halpern. “Our Path to Better Science in Less Time Using Open Data Science Tools,” Nature Ecology & Evolution 1, 0160 (2017) https://doi.org/10.1038/s41559-017-0160
   - Borer, Elizabeth T., Eric W. Seabloom, Matthew B. Jones, Mark Schildhauer. “Some Simple Guidelines for Effective Data Management,” Bulletin of the Ecological Society of America 90, no. 2 (2009): 205–214. https://doi.org/10.1890/0012-9623-90.2.205
   - White, Ethan P., Elita Baldridge, Zachary T. Brym, Kenneth J. Locey, Daniel J McGlinn, Sarah R. Supp. “Nine Simple Ways to Make it Easier to (Re)use Your Data,” Ideas in Ecology and Evolution 6, no. 2 (2013): 1–10. https://doi:10.4033/iee.2013.6b.6.f
   - Hayden, Thomas, and Michelle Nijuis. The Science Writers’ Handbook: Everything You Need t oKnow to Pitch, Publish, and Prosper in the Digital Age. Da Capo Lifelong Books, 2013.
   - “COMPASS homepage,” accessed September 29, 2021, https://www.compassscicomm.org/
